### ISSUE TITLE
Help needed - terraform outputs errors

### ISSUE THREAD

**Issue by Hax0rG1rl** [4ARMED/terraform-burp-collaborator#1]
Hi, 

I have followed your steps and I did what you have described. I have modified accordingly the terraform.tfvars file to contain my Amazon pub key exported from the initial pem format, my registered domain with the Amazon Route53, etc. 

Got terraform downloaded from the provided website and confirmed working properly, the burp pro package was placed into the right location. etc.

However, while I'm trying to initiate terraform plan I'm getting:

```
Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

1 error(s) occurred:

* provider.aws: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".


Error: error satisfying plugin requirements
```

+ when I'm trying to initiate the terraform init or terraform providers commands the following output is generated:

```
Error getting plugins: module root: 1 error(s) occurred:

* output 'name_servers': unknown resource 'data.aws_route53_zone.registered' referenced in variable data.aws_route53_zone.registered.name_servers
```
Do you have any ideas what is all about?  There are any technical updates regards this how-to or tricks which I might have forgotten during the config process? 

Thanks!

**Comment by marcwickenden** [comment]
Sounds to me like the domain wasn't registered with AWS originally. Is that the case? If it's not registered with AWS then Terraform won't be able to retrieve the AWS nameservers for the domain (as they aren't in AWS' control).

You should follow the instructions at https://github.com/4ARMED/terraform-burp-collaborator#non-aws-registered-domain if it's not an AWS domain. If it is an AWS domain, it could be a bug and I'll take a look.

Thanks!

**Comment by Hax0rG1rl** [comment]
Nope. The domain was registered with the  AWS Amazon Route53 from the very beginning. I did this last week just to avoid any pain in the neck regards this bit. 

Is there any debug switch which can be enabled and get more details for you?

Meanwhile, I will try to make a short movie for you just to see what's actually going on. Maybe that will helps more than a bunch of words. :)

**Comment by Hax0rG1rl** [comment]
I did the movie but I need an email address where I can send you the link.  Cheers.

**Comment by marcwickenden** [comment]
Can you email it to info at 4ARMED dot com and I’ll take a look ASAP?

**Comment by marcwickenden** [comment]
I've just pushed a commit. I think the outputs.tf file should reference 'burp' not 'registered'. Looks like I didn't clean that up properly when I was working on handling non-AWS domains.

I haven't been able to test it but can you give it a try?

If you git pull the update to outputs.tf or just manually change the affected file and let me know, that'd be great.

**Comment by marcwickenden** [comment]
For info https://github.com/4ARMED/terraform-burp-collaborator/commit/b48245671f6a3d4a2608c655656e166fd2a28456.

**Comment by Hax0rG1rl** [comment]
Solid copy. Thank you so much for your invested time. Will give it a try and keep you updated.

**Comment by marcwickenden** [comment]
BTW, in the video I think you had the availability zone specified in the region variable in your terraform.tfvars. That needs to be the region.

**Comment by Hax0rG1rl** [comment]
So, the main issue was resolved. All good now. I was able to deploy a private Colla Server. Thank you so much.
